version: 2

updates:
- package-ecosystem: "nuget"
  directory: "/dotnet"
  schedule:
    interval: "weekly"

- package-ecosystem: "pip"
  directory: "/python"
  schedule:
    interval: "weekly"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
